
# Step 1: Build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA', '.']

# Step 2: Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA']

# Step 3: Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    [
      'run',
      '--filename=gke.yaml',
      '--image=gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA',
      '--location=us-central1-a',
      '--cluster=gcp-devops-project',
      '--namespace=gcp-devops-project'
    ]

images:
  - 'gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA'
=======
  # 1. Build the real image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

  # 2. Push the real image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']

  # 3. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=gke.yaml
      # Tell gke-deploy to use the REAL image we just built
      - --image=gcr.io/$PROJECT_ID/gcpdevops
      - --location=us-central1-a
      - --cluster=gcp-devops-project
      - --namespace=gcp-devops-project
options:
  logging: CLOUD_LOGGING_O
