apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops-gke
  template:
    metadata:
      labels:
        app: gcp-devops-gke
    spec:
      containers:
      - name: gcp-devops-container
        # --- THIS IS THE FIX ---
        # This is a simple placeholder.
        # Your cloudbuild.yaml will replace this with the real image.
        image: gcpdevops-placeholder
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
